#!/bin/env Rscript

usage<-function()
{
	message(
"Usage: merge_summits.R <peak-file> [<outfile>]

This program reads a peak file generated by MACS2
in the format of NAME_peaks.xls (tab separated),
and then concatenates the parameters of multiple summits
in a same peak in one line.

<peak-file>: the input file.
<outfile>: optional outfile name, otherwise write to
standard output.

Author: Zhenguo Zhang
Created: Wed Jul 18 18:19:53 EDT 2018
"
			);
}


inputs<-commandArgs(T);
if(length(inputs) < 1)
{
	usage(); q("no");
}

library(data.table)

inFile<-inputs[1];
outFile<-ifelse(is.na(inputs[2]), "", inputs[2])

message("# Reading ", inFile)
peaks<-fread(paste("grep -v '^#'",inFile),sep="\t")

message("# Processing the data")
# get peak names and summit names
peaks[, peakName:=sub("^(.+?_peak_\\d+)(\\D{0,})$", "\\1", 
		name, perl=T)]
peaks[, summitName:=sub("^(.+?_peak_\\d+)(\\D{0,})$", "\\2",
		name,perl=T)]
# concatenate data for the same peak
idVars<-c("chr","start","end","peakName")
aggVars<-c("abs_summit","summitName","pileup","fold_enrichment",
		   "-log10(qvalue)", "-log10(pvalue)")
idFormula<-as.formula(paste(paste(idVars,collapse="+"), ".",sep="~" ))
results<-dcast(peaks, idFormula, fun=function(v)
         paste(v,collapse=","), value.var=aggVars)

write.table(results,outFile,sep="\t", quote=F, row=F)

message("# Job done")

